### ISSUE TITLE
Array interpolation in PHP - brackets are colored like string

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#347]
From https://github.com/Microsoft/vscode/issues/66231

```php
<?php
$x = $y[123]
echo "123$foo[123]456";
```

The brackets are colored gray on top, but green (the string color) on bottom.

![image](https://user-images.githubusercontent.com/323878/50868511-bc667780-1364-11e9-8939-dac649bb344c.png)

The problem seems to be that there is no specific color for "brackets" so when they are in a string, they fall back to the most specific available selector which is the color for strings.

**Comment by rsese** [comment]
Thanks for the report :+1:

@50Wliu I can reproduce in 1.34.0 but is this more a theme issue rather than an issue with the grammar?  E.g. since I can tweak the styles with something like:

```css
.syntax--php .syntax--string .syntax--array.syntax--begin,
.syntax--php .syntax--string .syntax--array.syntax--end {
  color: #abb2bf;
}
```

![arrays-in-strings](https://github-slack.s3.amazonaws.com/monosnap/test.php__worktest-tree-sitter_2019-01-10_16-44-33.png)
